server:
  port: 8101

#spring
spring:
  application:
    name: @project.artifactId@
  mvc:
    servlet:
      load-on-startup: 1

#info
info:
  app:
    name: ${spring.application.name}
    instance: ${eureka.instance.instance-id}
    build:
      artifactId: @project.artifactId@
      version: @project.version@

#endpoints
endpoints:
  enabled: true
  sensitive: false

#eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 5000

#ribbon
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
  ServerListRefreshInterval: 2

---
spring:
  profiles: provider
eureka:
  client:
    register-with-eureka: true
  instance:
      prefer-ip-address: false
      hostname: ${hostname:localhost}
      instance-id: ${eureka.instance.hostname}:${server.port}
