package com.msf.fuxi.xdiamond.persistence;

import com.msf.fuxi.xdiamond.domain.Profile;
import com.msf.fuxi.xdiamond.domain.ProfileExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProfileMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int countByExample(ProfileExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int deleteByExample(ProfileExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int insert(Profile record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int insertSelective(Profile record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  List<Profile> selectByExample(ProfileExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  Profile selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") Profile record,
                               @Param("example") ProfileExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int updateByExample(@Param("record") Profile record, @Param("example") ProfileExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(Profile record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table profile
   * @mbggenerated
   */
  int updateByPrimaryKey(Profile record);
}