package com.msf.fuxi.xdiamond.persistence;

import com.msf.fuxi.xdiamond.domain.RolePermission;
import com.msf.fuxi.xdiamond.domain.RolePermissionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RolePermissionMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int countByExample(RolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int deleteByExample(RolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("roleId") Integer roleId,
                         @Param("permissionId") Integer permissionId);
  
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int insert(RolePermission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int insertSelective(RolePermission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  List<RolePermission> selectByExample(RolePermissionExample example);
  
  /**
   * 根据 roleId和permissionId查询关系
   * @param rolePermission
   * @return
   */
  RolePermission selectRolePermission(@Param("roleId") Integer roleId, @Param("permissionId") Integer permissionId);
  /**
   * 查询当前权限是否绑定角色
   * @param roleId
   * @return
   */
  int selectCountByPermissionId(@Param("permissionId") Integer permissionId);
  
  /**
   * 删除该角色下所有绑定的权限关系
   * @param roleId
   * @return
   */
  int delectByRoleId(@Param("roleId") Integer roleId);
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") RolePermission record,
                               @Param("example") RolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  int updateByExample(@Param("record") RolePermission record,
                      @Param("example") RolePermissionExample example);
}